FROM golang:1.24.3 AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o grpcserver ./cmd/grpcserver

FROM debian:bookworm-slim 
WORKDIR /app
COPY --from=build /app/grpcserver .
EXPOSE 50051

CMD [ "./grpcserver" ]
